---
# TSS-seq configuration file
#
# relative paths are okay
#
# for the experimental genome only, except for 'spikein_fasta'
genome:
    annotation_workflow: ../build-annotations-cerevisiae/  # path to Snakemake workflow used to build annotations of genic, convergent, divergent, etc. regions using the same fasta and annotation files listed above

spike_in:
    name: Spom
    proportion: 0.1
    fasta: ../genomefiles_cerevisiae/S_pombe.ASM294v2.fa

# sample metadata
samples:
    non-depleted-1:  # [STRING] sample name. Do not use underscores ("_").
        fastq: fastq/AS1_S17.R1.fastq.gz  # path to raw fastq file
        group: non-depleted  # [STRING] sample group tag. Do not use underscores ("_").
        pass-qc: True  # [True|False] Should this sample be used for peakcalling, and included in "passing" heatmaps, metagenes, scatter plots, etc? Leave True for initial pipeline run, and rerun pipeline with False if a sample fails quality controls.
        spikein: True  # [True|False] Does the sample have a spikein?
    non-depleted-2:
        fastq: fastq/AS3_combined.R1.fastq.gz
        group: non-depleted
        pass-qc: False
        spikein: True
    non-depleted-3:
        fastq: fastq/T01_S1_L001_R1_001.fastq.gz
        group: non-depleted
        pass-qc: True
        spikein: True
    non-depleted-4:
        fastq: fastq/T02_S2_L001_R1_001.fastq.gz
        group: non-depleted
        pass-qc: True
        spikein: True
    non-depleted-5:
        fastq: fastq/T03_S3_L001_R1_001.fastq.gz
        group: non-depleted
        pass-qc: True
        spikein: True
    depleted-1:
        fastq: fastq/AS2_S18.R1.fastq.gz
        group: depleted
        pass-qc: True
        spikein: True
    depleted-2:
        fastq: fastq/AS4_S20.R1.fastq.gz
        group: depleted
        pass-qc: True
        spikein: True

# comparisons to be made in differential expression, motif enrichment, data visualization, scatterplots, etc, etc.
comparisons:
    libsizenorm:
        - depleted: non-depleted  # CONDITION: CONTROL . Tags must match 'group' tags in sample metadata
    spikenorm:
        - depleted: non-depleted  # It's okay to have no comparisons if no spikein normalized comparisons are to be made

# [INT] binsizes for scatterplots
scatterplot_binsizes:
    - 1
    - 10

# cutadapt settings
cutadapt:
    trim_qual: 25  # [INT] quality cutoff for cutadapt 3' trimming
    adapter: CTGTAGGCACCATCAAT  # 3' adapter sequence, from 5' to 3'

# tophat2 alignment settings
tophat2:
    index-path: ../genome/bowtie2_indexes  # directory to create index files, if they don't already exist in that directory
    read-mismatches: 3  # [INT]
    read-gap-length: 2  # [INT]
    read-edit-dist: 3  # [INT]
    min-anchor-length: 8  # [INT]
    splice-mismatches: 1  # [INT]
    min-intron-length: 20  # [INT]
    max-intron-length: 5000  # [INT]
    max-insertion-length: 3  # [INT]
    max-deletion-length: 3  # [INT]
    max-multihits: 100  # [INT]
    segment-mismatches: 3  # [INT]
    segment-length: 20  # [INT]
    min-coverage-intron: 50  # [INT]
    max-coverage-intron: 10000  # [INT]
    min-segment-intron: 50  # [INT]
    max-segment-intron: 500000  # [INT]

# peakcalling settings
peakcalling:
    bandwidth: 10  # [INT] bandwidth of Gaussian kernel used in pilot density estimation
    local-bg-window: 2000  # [INT] size, in nt, of window upstream of peak used for local lambda
    idr: 0.1  # [FLOAT in (0,1)] irreproducible discovery rate cutoff

# DESeq2 differential expression settings
deseq:
    fdr: 0.1  # [FLOAT in (0,1)] false discovery rate threshold
    fold-change-threshold: 1.5  # [FLOAT] fold-change for hypothesis. Absolute fold-change, NOT log2(FC).

# gene ontology settings
run_gene_ontology: True  # [True|False] Run gene ontology analyses?
gene_ontology_mapping_file: ../genome/go_slim_mappings/pombase_go_slim_mapping_filtered_2018_2_7.tsv  # path to GO mapping file, a 3-column, tab-delimited file: {common name}\t{standard name}\t{GO category ID}\n

# TSS sequence information settings
consensus:
    window: 20  # [INT] nucleotides around EACH side of TSSs to make sequence logo

# motif analysis settings
motifs:
    run_motif_analyses: False  # [True|False] Run motif analyses?
    enrichment-upstream: 200  # [INT] basepairs upstream of TSS-seq peak summits to search for motif enrichment
    enrichment-downstream: 0  # [INT] basepairs downstream of TSS-seq peak summits to search for motif enrichment
    enrichment-fdr: 0.01  # [FLOAT in (0,1)] false discovery rate for testing motif enrichment (Fisher's exact test, 2-tailed)
    meme-chip:  # MEME-ChIP settings
        run-meme-chip: False # [True|False] Run de novo motif discovery?
        upstream: 100 # [INT] basepairs upstream of TSS-seq peak summits to search for de novo motifs
        downstream: 30 # [INT] basepairs downstream of TSS-seq peaks summits to search for de novo motifs
        meme-mode: zoops  # [oops|zoops|anr]
        meme-nmotifs : 10  # [INT] maximum number of motifs to find with MEME

# data visualization settings
plot_figures: True  # [True|False] plot heatmaps and metagenes?
figures:
    allcoding-TSS:  # [STRING] name of figure. Do not include underscores ("_")
        annotations:
            coding-genes:  # [STRING] name of region. Do not include underscores ("_"). More than one region can be plotted.
                path: ../genome/annotations/S_pombe_codingtranscripts-adjustedTSS.bed  # path to BED6 file of regions
                label: coding genes  # [STRING] label for region
                n_clusters: 1  # [INT] number of clusters to separate region into. Leave 1 for no clustering. Basic k-means clustering is used.
        parameters:
            type: absolute  # [absolute|scaled] Plot absolute distances, or scale all annotations to the same length. See below for example parameters for a scaled plot.
            binsize: 20  # [INT] binsize to summarise data
            binstat: mean  # [mean|median|min|max|sum|std] operation used to summarise data
            refpoint: TSS  # [TSS|TES|center] reference point in region. TSS and TES correspond to the 5' and 3' ends, respectively.
            refpointlabel: TSS  # [STRING] label for reference point
            upstream: 500  # [INT] nucleotides upstream of reference point to plot. Must be a multiple of the binsize.
            dnstream: 4000  # [INT] maximum nucleotides downstream of reference point to plot. Must be a multiple of the binsize.
            nan_afterend: True  # [True|False] Should data after the end of the annotation be left out? Useful for length-sorted heatmaps.
            pct_cutoff: .995  # [FLOAT in (0,1)] Percentile of the data to set as the maximum of the colorbar in heatmaps
            log_transform: False  # [True|False] Log transform data?
            spread_type: conf_int  # [conf_int|quantile] Plot 95% confidence interval of the mean, or quantiles of the data.
            trim_pct: 0.01  # [FLOAT in (0,1)] For confidence intervals, this is the percent to winsorize before taking the mean. For quantiles, this is the lower quantile.
            arrange: length  # [no|length|cluster] No: keep annotations in order of annotation file. Length: sort annotations in order of length before plotting. Cluster: try to plot annotations with similar data close to one another, using optimal leaf ordering of hierarchical clustering
            # cluster_conditions:
            #   depleted: sense  # CONDITION: STRAND. If arrange: cluster, the condition and strand to be used for arranging. Strand can be "sense", "antisense", or "both".
            #   non-depleted: both
            # cluster_five: -500  # [INT] 5' boundary of the data to be used for clustering, relative to the reference point.
            # cluster_three: 500  # [INT] 3' boundary of the data to be used for clustering, relative to the reference point
            heatmap_colormap: inferno  # [viridis|inferno|magma|plasma] colormap for heatmaps
    allcoding-scaled:
        annotations:
            coding-genes:
                path: ../genome/annotations/S_pombe_codingtranscripts-adjustedTSS.bed
                label: coding genes
                n_clusters: 1
        parameters:
            type: scaled  # [absolute|scaled] Plot absolute distances, or scale all annotations to the same length. See above for example parameters for an absolute distance plot.
            binsize: 20  # [INT] binsize to summarise data
            binstat: mean  # [mean|median|min|max|sum|std] operation used to summarise data
            scaled_length: 2000  # [INT] length, in nt, to scale all annotations to
            refpointlabel: TSS  # [STRING] label for 5' end of scaled annotations
            three_prime_label: CPS  # [STRING] label for 3' end of scaled annotations
            upstream: 500  # [INT] nucleotides upstream of 5' end of annotations to plot. Must be a multiple of the binsize.
            dnstream: 500  # [INT] nucleotides downstream of 3' end of annotations to plot. Must be a multiple of the binsize.
            pct_cutoff: .995  # [FLOAT in (0,1)] Percentile of the data to set as the maximum of the colorbar in heatmaps
            log_transform: False  # [True|False] Log transform data?
            spread_type: conf_int  # [conf_int|quantile] Plot 95% confidence interval of the mean, or quantiles of the data.
            trim_pct: 0.01  # [FLOAT in (0,1)] For confidence intervals, this is the percent to winsorize before taking the mean. For quantiles, this is the lower quantile.
            arrange: length  # [no|length|cluster] No: keep annotations in order of annotation file. Length: sort annotations in order of length before plotting. Cluster: try to plot annotations with similar data close to one another, using optimal leaf ordering of hierarchical clustering
            # cluster_conditions:
            #   depleted: sense  # CONDITION: STRAND. If arrange: cluster, the condition and strand to be used for arranging. Strand can be "sense", "antisense", or "both".
            #   non-depleted: both
            # cluster_five: -500  # [INT] 5' boundary of the data to be used for clustering, relative to the 5' end of the annotation.
            # cluster_three: 500  # [INT] 3' boundary of the data to be used for clustering, relative to the 3' end of the annotation.
            heatmap_colormap: inferno  # [viridis|inferno|magma|plasma] colormap for heatmaps

# maximum number of threads to use if running locally
threads: 4  # [INT]
