name: snakemake_default
channels:
    - bioconda
    - conda-forge
    - https://repo.anaconda.com/pkgs/free/linux-64
    - https://repo.anaconda.com/pkgs/free/noarch
    - https://repo.anaconda.com/pkgs/pro/linux-64
    - https://repo.anaconda.com/pkgs/pro/noarch
    - nodefaults

dependencies:
    - snakemake=5.1.5
    - gawk=4.2.1
    - sed=4.4
    - bc=1.06
    - pigz=2.3.4
    - cutadapt=1.16
    - samtools=1.7
    - pysam=0.14.1
    - bedtools=2.27.1
    - deeptools=2.5.3
    - meme=4.12.0
    - fastqc=0.11.7
    - r-argparse=1.0.4
    - r-tidyverse=1.1.1
    - r-ggseqlogo=0.1

